version: '3.8'

services:
  edunori-db:
    image: mysql:8
    container_name: edunori-db
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - edunori-db-data:/var/lib/mysql
      - ./edunori_dev_dump.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: edunori_dev
      MYSQL_USER: edunori
      MYSQL_PASSWORD: root25

  edunori-app:
    build: .
    container_name: edunori-app
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - edunori-db
    env_file:
      - .env.local
    environment:
      EDUNORI_DB_HOST: edunori-db
      EDUNORI_DB_PORT: 3306
      EDUNORI_DB_USERNAME: edunori
      EDUNORI_DB_PASSWORD: root25
      EDUNORI_DB_DATABASE: edunori_dev

volumes:
  edunori-db-data:
