version: '3.8'

services:
  # 🐬 Edunori MySQL (local DB for Edunori users + interests)
  db:
    image: mysql:8.0
    container_name: edunori-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root25
      MYSQL_DATABASE: edunori_dev
      MYSQL_USER: edunori
      MYSQL_PASSWORD: root25
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  # 🦄 Edunori API (NestJS backend)
  edunori-app:
    container_name: edunori-app
    build: .
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: edunori
      DB_PASSWORD: root25
      DB_DATABASE: edunori_dev

volumes:
  mysql-data:

